import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Dispatch SPA build output (regenerated by `npm run build:dispatch`).
    // Same files as out/, just copied under public/dispatch/ so the existing
    // Workers static-assets binding can serve them at /dispatch/*.
    "public/dispatch/**",
  ]),
]);

export default eslintConfig;
